### ISSUE TITLE
Index out of range-error after starting new update

### ISSUE THREAD

**Issue by alexgtech** [cadon/ARKStatsExtractor#158]
I'm getting the following error popup message after replacing my executable and the json script.

http://imgur.com/a/UUV8O

**Comment by cadon** [comment]
Hi, thanks for the report. There are many possibilities what that could be.

* Does the popup appear immediately after starting the application or did you do something before?
* Do you have a library that autoloads when starting?
* Do you have saved timers?
* Can you open other libraries / create a new one?

If that error appears right after opening the app, can you send the library file for further investigation?

**Comment by Krakin** [comment]
I am also receiving this error with the new 0.20.11.2 update. 


Does the popup appear immediately after starting the application or did you do something before?
   - Immediately after launching.

Do you have a library that autoloads when starting?
   - The library does not auto-load, I also tried deleting the library from the save folder and that didn't affect 0.20.11.2

Do you have saved timers?
   - No

Can you open other libraries / create a new one?
   - Can't launch it at all in 0.20.11.2

   - I can in 0.20.11.1

**Comment by Mai7viac** [comment]
I'm getting the same error. As soon as I extract the files to a folder and click the .exe, I get the same error that alexgtech posted. Is there a certain place you need to install the application?

**Comment by Darinth** [comment]
I'm have the same issues described here.
Does the popup appear immediately after starting the application or did you do something before?
- Immediately after launching

Do you have a library that autoloads when starting?
- Yes I do, though I'm having issues finding the setting to disable the autoload.

Do you have saved timers?
- No I do not

Can you open other libraries / create a new one?
- I took the following steps in diagnosing the issue: I copied 0.20.11.1 into my stats extractor directory and opened it, it loads fine. I then created a temp.xml library. I closed the stats extractor and reopened it to confirm that doing so changed the default library it loads. Temp.xml, which is a new empty library, now loads as the default library. I then closed the stats extractor and put the 0.20.11.2 version and got the message again. Doesn't appear to be library dependent. Using the 0.20.11.1 version for the moment. 

Attached my library for diagnostics anyways. :)

[Creatures.zip](https://github.com/cadon/ARKStatsExtractor/files/746794/Creatures.zip)

**Comment by cadon** [comment]
Thanks for all the descriptions!

I still cannot reproduce it. My next guess is, that it's related to the user-settings. There are some settings that are saved as arrays, maybe there's an index out of range. Can you try to delete or move the folder `%localappdata%\ARKBreedingStats` and try if it runs with vanilla settings? Keep in mind, the settings is where global settings of the tool are saved, like modified stat-weightings for the breeding-planner, so better make a backup if you want to keep these (the other values are not as important, e.g. windows-position and -size).

**Comment by Mai7viac** [comment]
So for me, I did a clean install last night (just built a new computer).
I'll check for that folder when I get home.

The other thought I had was that I have ark on a separate hdd than the ssd
I installed the extractor on, would that make a difference?

Thanks for looking into it

CF

**Comment by cadon** [comment]
The location doens't affect that. The settings-folder is always the same on windows.

**Comment by Krakin** [comment]
The issue is fixed on my end, all I did was restart my computer.

I believe it may be somehow connected between installing the last two updates without doing so.

**Comment by Mai7viac** [comment]
Ok, so what Krakin said works. Got home after work and booted my computer. Clicked the .exe and it came up just fine. Not sure what happens, but apparently a restart is needed for it to work.

**Comment by Darinth** [comment]
That's really confusing and surprising, but sure enough I just loaded up my computer looked at this issue, installed 0.20.11.2 again and it works perfectly now.

**Comment by cadon** [comment]
Good to hear it seems to be solved. I've still no idea where that issue came from, there were no changes regarding the settings or other global parameters. I'll close this for now, just reopen / comment if it appears again.

**Comment by Pyr088** [comment]
Restarting didnt seem to change anything for me. I'm getting the error immediately when opening the program. I have tried to move the appdata folder and opening and its still happening. I can open older versions but not this one.

**Comment by ronindesign** [comment]
I'm getting same error.

**Comment by cadon** [comment]
I've created a debug-version, that should help to track this error down. It has some messageboxes that tells at which point in the process the tool currently is. If you can write which message shows directly before the error appears, I should be able to see in which block that issue is caused. Thanks for helping out. I've never seen this error on my computer, so people with that error should give this a try.

[ARK Smart Breeding_debug-version.zip](https://github.com/cadon/ARKStatsExtractor/files/753345/ARK.Smart.Breeding_debug-version.zip)

**Comment by ronindesign** [comment]
It might also be worth noting that I started getting the (windows 10) security warning about 'are you sure you want to run this app'. Testing your debug version now.

**Comment by ronindesign** [comment]
Ran debug, didn't see any message boxes: http://i.imgur.com/D6gSgkH.png

**Comment by cadon** [comment]
Thanks, so the error appears before the form is loaded.

Hm, did the warning just came up recently? I haven't changed anything that should trigger that warning. I guess it's the general warning for apps that were downloaded.

**Comment by ronindesign** [comment]
The warning I believe appears on first run of .exe (not sure in what circumstances) but for example it comes up everytime when running exe directly from zip (i.e. reextracted new each run) but only once if I run after extracting to location. Also, I found a log, not sure if it's of any use:

```1,"fusion","GAC",0
1,"WinRT","NotApp",1
3,"System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System\f2f2574e2dbdc45a50abc13c1cec329d\System.ni.dll",0
3,"System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Drawing\e3682d99c2e9ec868d59164da808a1b5\System.Drawing.ni.dll",0
3,"System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\5b3b8549052ad9c7ccf1567cdc227bee\System.Windows.Forms.ni.dll",0
3,"System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Core\8da767622e632555f83803260174a48f\System.Core.ni.dll",0
3,"System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Configuration\6fc9defdc2240055a039dd8ee6fb5533\System.Configuration.ni.dll",0
3,"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Xml\bb0c1c3444e35a126fc0441b854345c1\System.Xml.ni.dll",0
3,"System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Runteb92aa12#\45dd2041947f99e66a1776d63169d4c2\System.Runtime.Serialization.ni.dll",0
3,"SMDiagnostics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\SMDiagnostics\ddfc3eb4630fdd39aed4a0df0797f372\SMDiagnostics.ni.dll",0
3,"System.ServiceModel.Internals, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Servd1dec626#\613e92f8b240b9a913b1b3a537e738ea\System.ServiceModel.Internals.ni.dll",0
3,"Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Accessibility\d9b4c430c821f4504e1cafe4a4c90f18\Accessibility.ni.dll",0
```

**Comment by cadon** [comment]
Can you try this debug-version?
[ARK Smart Breeding_debug-version2.zip](https://github.com/cadon/ARKStatsExtractor/files/753354/ARK.Smart.Breeding_debug-version2.zip)

**Comment by ronindesign** [comment]
Got 'Starting to init form'.
Then crash message.

**Comment by ronindesign** [comment]
Event View log:

```
Application: ARK Smart Breeding.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at ARKBreedingStats.CreatureInfoInput.dhmInputGrown_TextChanged(System.Object, System.EventArgs)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Windows.Forms.Control.OnTextChanged(System.EventArgs)
   at System.Windows.Forms.MaskedTextBox.OnTextChanged(System.EventArgs)
   at System.Windows.Forms.MaskedTextBox.SetWindowText(System.String, Boolean, Boolean)
   at System.Windows.Forms.MaskedTextBox.Replace(System.String, Int32, Int32)
   at System.Windows.Forms.MaskedTextBox.set_Text(System.String)
   at ARKBreedingStats.uiControls.dhmInput.set_Timespan(System.TimeSpan)
   at ARKBreedingStats.CreatureInfoInput.set_Grown(System.DateTime)
   at ARKBreedingStats.Form1.InitializeComponent()
   at ARKBreedingStats.Form1..ctor()
   at ARKBreedingStats.Program.Main()
```

**Comment by cadon** [comment]
oh, so it's at the very beginning. Can you try this one? it should give a better error-message for that.

[ARK Smart Breeding_debug-version3.zip](https://github.com/cadon/ARKStatsExtractor/files/753359/ARK.Smart.Breeding_debug-version3.zip)

**Comment by cadon** [comment]
oh nevermind, I just read the event-view-log you posted, that should lead to the error.

**Comment by ronindesign** [comment]
Same, got 'Starting to init form', then crash msg. Log viewer stack trace:

```
Application: ARK Smart Breeding.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at ARKBreedingStats.CreatureInfoInput.dhmInputGrown_TextChanged(System.Object, System.EventArgs)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Windows.Forms.Control.OnTextChanged(System.EventArgs)
   at System.Windows.Forms.MaskedTextBox.OnTextChanged(System.EventArgs)
   at System.Windows.Forms.MaskedTextBox.SetWindowText(System.String, Boolean, Boolean)
   at System.Windows.Forms.MaskedTextBox.Replace(System.String, Int32, Int32)
   at System.Windows.Forms.MaskedTextBox.set_Text(System.String)
   at ARKBreedingStats.uiControls.dhmInput.set_Timespan(System.TimeSpan)
   at ARKBreedingStats.CreatureInfoInput.set_Grown(System.DateTime)
   at ARKBreedingStats.Form1.InitializeComponent()
   at ARKBreedingStats.Form1..ctor()
   at ARKBreedingStats.Program.Main()
```

**Comment by cadon** [comment]
Does this work now?

[ARK Smart Breeding_debug-version4.zip](https://github.com/cadon/ARKStatsExtractor/files/753371/ARK.Smart.Breeding_debug-version4.zip)

**Comment by ronindesign** [comment]
Nope, got:

```
Application: ARK Smart Breeding.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at ARKBreedingStats.CreatureInfoInput.dhmInputGrown_TextChanged(System.Object, System.EventArgs)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Windows.Forms.Control.OnTextChanged(System.EventArgs)
   at System.Windows.Forms.MaskedTextBox.OnTextChanged(System.EventArgs)
   at System.Windows.Forms.MaskedTextBox.SetWindowText(System.String, Boolean, Boolean)
   at System.Windows.Forms.MaskedTextBox.Replace(System.String, Int32, Int32)
   at System.Windows.Forms.MaskedTextBox.set_Text(System.String)
   at ARKBreedingStats.uiControls.dhmInput.set_Timespan(System.TimeSpan)
   at ARKBreedingStats.CreatureInfoInput.set_Grown(System.DateTime)
   at ARKBreedingStats.Form1.InitializeComponent()
   at ARKBreedingStats.Form1..ctor()
   at ARKBreedingStats.Program.Main()
```

**Comment by cadon** [comment]
phew, a bit cumbersome to debug like this, but it'd be great to finally get this solved. next try :)

[ARK Smart Breeding_debug-version5.zip](https://github.com/cadon/ARKStatsExtractor/files/753404/ARK.Smart.Breeding_debug-version5.zip)

**Comment by ronindesign** [comment]
Yep, looks like that one worked, let me test again I'll update in less than 30 min.

**Comment by ronindesign** [comment]
Perfect, added json from v0.21 release, works great! Started right up no errors.

**Comment by cadon** [comment]
Great! The fixed version is released. Thanks a lot to all that helped to resolve this!
